---

global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-dcos-forwarder'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.


# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'federate'
  #   scrape_interval: 15s

  #   honor_labels: true
  #   metrics_path: '/federate'

  #   params:
  #     'match[]':
  #       - '{job="prometheus"}'
  #       - '{__name__=~"job:.*"}'

  #   static_configs:
  #     - targets:
  #       - 'prometheus-slave:9090'